### ISSUE TITLE
appears the recursion is only 1 level deep.

### ISSUE THREAD

**Issue by geetee24** [BePo65/license-report-recursive#34]
Need infinite recursion.  Current code only lists parent's child's dep.

**Comment by BePo65** [comment]
The program should analyze the dependencies of a program and the dependencies of the dependencies through all levels.

What commandline did you use?
What project (if I could find it on github)`?

For large projects the program will take quite a while - so be patient.

**Comment by BePo65** [comment]
Closed as stale.
